version: '3.8'

services:

  nginx:
    build: services/nginx
    ports:
      - 80:80
    depends_on:
      - web  
  web:
    build:
      context: services/web
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes: 
      - dataframe-data:/app
    expose:
      - 5000
    environment:
      - FLASK_APP=api/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=api.config.DevelopmentConfig
volumes:
  dataframe-data: